@Day1WebApi_HostAddress = http://localhost:5075
# @Day1WebApi_HostAddress = http://localhost:5000
@AccessToken = CfDJ8AhvjefdrPhDu-nDFsJRfqiG_OcqNq3CJq3dNHVpzAMx1Zn1eViEnX-LFoZQznp47H3JSn5X1aGk0cJayeEqHO3_3iSxn5BTmKHNoRLhHyyLi2G-uErMiHfoVXfLeWgHxnm-N8mLCp2Z0SG8-0ORCaA0wxahb5uHscHe7IIKW29drXk8NXu_ZXsUVsXvvJTI053V2oDhTwUskv4pSoZAQ9IidN7UWTg4IJsDT2UEmBvLNHaRsYWm_tYVrvvwGFWAfsHKuwQIOm9mocQZnD9-qUWddUm7XCrD8eo73czJbsy0_gHI03Ob9wEnCdVPhGY2lROsePg0nRs1K8h4jtJItUf_Q0pvBsN7a7jtPJnHcN5CmVyOE4JJDmORctgM73ptRTLXs8hHLxLkRcJhJnt4FpNpkDSgqEDiniJ0ugwdYsazowPJjtZ4-c5JVK2X7ma5de5w_8O4bTcdm-_ev-16qdEygm2-yRK_sQHgpJ17JbUmmPObarSasIYPLH9SUc2Bv8cm3w7EUPO3wPpltoPwlH-yxHwK2oYOEBqHJmkZBRibfeQENKj74LcrVN-1aCmzHTtAkQnAdpS9BbkS4WNFAXZdSSzZm-h257eoM4Q3njrYe8Zg22DeEb1jb5CbUU5SnjZCEJ0o3sXzXVQEt-yxmwMoTLSVRznVGkKAErdCAg8hvl6-K05Wc0KgqKj-0pdCLH5czXv60ryzkUTcjFFftY3rlk2btOWH3NA9ivV7WRMKEUz0iUixKoYWqDPssfsTtQJcgjB4sL9169-Amc55uOiewtG1l8d1PEuBsy3onym9y7b3V2x-SCXomo10M5xqsg

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "1234",
  "password": "Password123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/7275a355-d15e-4c0b-9d20-76738715e131
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

####

PUT {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Administrator",
  "gaji": 3000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "email": "gufron.dian@kemenkeu.go.id",
  "roleName": "Admin"
}

###

GET {{Day1WebApi_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Account/register-pegawai
Accept: application/json
Content-Type: application/json

{
  "nama": "Budi",
  "nip": "1234",
  "jabatan": "Staff",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12",
  "email": "budi@example.com",
  "password": "Password123!"
}

###

DELETE {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Day1WebApi_HostAddress}}/api/Account/manage/info-pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Day1WebApi_HostAddress}}/api/Kategori/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "nama": "string"
}

###

GET {{Day1WebApi_HostAddress}}/api/Aset
Accept: application/json
Content-Type: application/json
