# @Day1WebApi_HostAddress = http://localhost:5075
@Day1WebApi_HostAddress = http://localhost:5000
@AccessToken = CfDJ8AhvjefdrPhDu-nDFsJRfqialI20G6QaLgI_fM7t_d3Urmvn3U3dkU_7AgyKDV5BJEzbULEuaz1KqSlUh_vaBl2ogXs3PU84dFt-zcTfaPvM47gGDv0Lq9f84ZIX_Y-mmyZBMqu8meeOwO94CSPB-IWpdG5D2fpieaR9gkAql8drl23RzEQJ542Nt0LvCDmw6IH-tZ3QLypHkEna_eD9p-ogzjN_pdPAkDGlwvhJcHMtMDDgIy_02ozzJSrQM71UuJvI_43A-QjcvG-Hsgj3G0pZrpoXVv-oeTFSOGmMYcJb1UyuDwXGMl2paxTieWxkmFkSnjzXi6ZFIzPNknU-QVcvpjY3AIdGbGr71DKlw-Je9zku7yozyYEQoA5EMdOc51ReNQd2JZb2uIQzwYAf56vItCQ6JVSAB3wPbZ3pqJHFaQkQJ5c-NUZlqLTECEmTUljjG5fxr3HYaKql1mpcTlyeap0lA5jHwihuqtTe8P4AgytsipSjQz7xzBGcvpqHYh6eFBNMT6teBjKfAmDt6OocQcmx-z_059U5ee-svXKUAnLJ8Zcf8oweyZ2dowmtvWuUbAia2SONqY66SjEM1rf_25lBkEzbaRFRiLCPBlfTM3exYcFOY4W2I7lAIvzG5dlFQarXN1Htzke2sRsD-3XqLuulJEFEajwTgGsFG_HkOtVnbE04pYwqqhUMpfmtJozR9wl9kpk5qjoVHH04ZKLESuIJvEncvbGgsZVPmHITBTYfJfAy9h8XVsCBHRLsA9_MojcB4tLIzeaYmIPXVKONYdv63Gl8JBM7kienrmtB6zIRq3qkjE1c4NbKc2zfcg

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "1234",
  "password": "Password123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/7275a355-d15e-4c0b-9d20-76738715e131
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

####

PUT {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Administrator",
  "gaji": 3000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "email": "budi@example.com",
  "roleName": "Admin"
}

###

GET {{Day1WebApi_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Account/register-pegawai
Accept: application/json
Content-Type: application/json

{
  "nama": "Budi",
  "nip": "1234",
  "jabatan": "Staff",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12",
  "email": "budi@example.com",
  "password": "Password123!"
}

###

DELETE {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Day1WebApi_HostAddress}}/api/Account/manage/info-pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Day1WebApi_HostAddress}}/api/Kategori/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "nama": "string"
}

###

GET {{Day1WebApi_HostAddress}}/api/Aset
Accept: application/json
Content-Type: application/json
